name: Node.js CI with Forced Install

on:
  push:
    branches: [ "main", "develop", "release", "templates" ]
  pull_request:
    branches: [ "main", "develop", "release", "templates" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Force install dependencies
        run: npm i --force
      
      - name: Run build
        run: npm run build --if-present
      
      - name: Run tests
        run: npm test
