name: Node.js CI with Environment

on:
  push:
    branches: [ "main", "develop", "release", "templates" ]
  pull_request:
    branches: [ "main", "develop", "release", "templates" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Create .env file
        run: |
          cat << EOF > .env
          # MongoDB Configuration
          MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
          MONGO_PORT=${{ secrets.MONGO_PORT }}
          
          # App Configuration
          NODE_ENV=test
          JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          PORT=3000
          EOF

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get remove -y containerd docker.io
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          docker --version
          docker compose version

      - name: Run tests with Docker
        run: docker-compose up -d --build
      
      - name: Force install dependencies
        run: npm i --force

      - name: Run ESLint tests
        run: npx eslint .
      
      - name: Run tests
        run: npm test
