name: Node.js CI with Environment

on:
  push:
    branches: [ "main", "develop", "release", "templates" ]
  pull_request:
    branches: [ "main", "develop", "release", "templates" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          docker --version
          docker-compose --version
      
      - name: Create .env file
        run: |
          cat << EOF > .env
          # MongoDB Configuration
          MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
          MONGO_PORT=${{ secrets.MONGO_PORT }}
          
          # App Configuration
          NODE_ENV=test
          JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          PORT=3000
          EOF
      
      - name: Force install dependencies
        run: npm i --force

      - name: Run tests with Docker
        run: docker-compose up -d --build

      - name: Run ESLint tests
        run: npx eslint .
      
      - name: Run tests
        run: npm test
